### ISSUE TITLE
Install Jupyter notebooks via ansible

### ISSUE THREAD

**Issue by ckunki** [exasol/data-science-sandbox#16]
After  notebook files have been moved to a different folder as requested by ticket #53 the current ticket requests to 

```[tasklist]
### Tasks
- [x] Install Jupyter notebooks via ansible into the Docker container, too
- [x] Add a test verifying the notebooks to be available in Docker Container
- [x] Move files in `exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/` to sub-folder `slc`
```

* Move files in `exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/` to sub-folder `slc`: 
  * `slc_main_build_steps.svg`
  * `bash_runner.py`
  * `script-languages.ipynb`
