### ISSUE TITLE
Rename all occurences of script-languages-developer-sandbox to data-science-sandbox

### ISSUE THREAD

**Issue by ckunki** [exasol/data-science-sandbox#5]
```[tasklist]
### Tasks
- [x] Rename folder `exasol_script_languages_developer_sandbox` to `exasol/ds/sandbox`
- [x] in file `eslds/lib/ansible/ansible_repository.py`: rename `default_repositories = (AnsibleResourceRepository ( exasol_script_languages_developer_sandbox.runtime.ansible ),)` to ?
- [x] in file `eslds/lib/render_template.py`: rename `jinja2.Environment(loader=jinja2.PackageLoader("exasol_script_languages_developer_sandbox"),` to ?
- [x] in file `test/test_motd_jupyter_template.py`: rename `src_path = Path(__file__).parent.parent / "exasol_script_languages_developer_sandbox" / "runtime" /` to ?
- [x] in file `.github/workflows/test_release.yml`: rename `run: poetry run python3 -m exasol_script_languages_developer_sandbox.main start-test-release-build --release-title "${{ github.event.inputs.release_title }}" --branch "$GITHUB_REF"` to ?
- [x] in file `.github/workflows/release_droid_upload_github_release_assets.yml`: rename `run: poetry run python3 -m exasol_script_languages_developer_sandbox.main` to ?
- [x] in file `eslds/lib/asset_id.py`: rename `stack_prefix="EC2-SLC-DEV-SANDBOX-", ami_prefix="Exasol-SLC-Developer-Sandbox")` to ?
- [x] in file `eslds/lib/asset_id.py`: rename `BUCKET_PREFIX = "slc_developer_sandbox"` to ?
- [x] in file `eslds/lib/export_vm/rename_s3_objects.py`: rename `return "{bucket_prefix}exasol-script-languages-developer-sandbox-{asset_id}.{img_format}"` to `exasol-data-science-sandbox-{asset_id}.{img_format}`
- [x] in file `eslds/lib/export_vm/rename_s3_objects.py`: rename docstring ` The destination objects always have the format "exasol-script-languages-developer-sandbox-{asset_id}.{img_format}"` to `exasol-data-science-sandbox-{asset_id}.{img_format}`
- [x] in file `eslds/lib/github_release_access.py`: rename `gh_repo = gh.get_repo("exasol/script-languages-developer-sandbox")` to `exasol/data-science-sandbox`
- [x] in file `eslds/lib/setup_ci_codebuild/ci_codebuild.py`:: rename `STACK_NAME = "DEVELOPER-SANDBOX-CI-TEST-CODEBUILD"` to ?
- [x] in file `eslds/lib/setup_release_codebuild/release_codebuild.py`: rename `RELEASE_CODE_BUILD_STACK_NAME = "DEVELOPER-SANDBOX-RELEASE-CODEBUILD"` to ?
- [x] in file `eslds/lib/vm_bucket/vm_slc_bucket.py`: rename `STACK_NAME = "DEVELOPER-SANDBOX-VM-SLC-Bucket"` to ?
- [x] in file `eslds/lib/vm_bucket/vm_slc_bucket_waf.py`: rename `STACK_NAME = "DEVELOPER-SANDBOX-VM-SLC-Bucket-WAF"` to ?
- [x] in file `test/aws_mock_data.py`: rename `'StackName': "DEVELOPER-SANDBOX-VM-SLC-Bucket",` to ?
- [x] in file `test/aws_mock_data.py`: rename `''StackName': "DEVELOPER-SANDBOX-VM-SLC-Bucket-WAF",` to ?
- [x] in file `test/test_ci.py`: rename `@pytest.mark.skipif(os.environ.get('RUN_DEVELOPER_SANDBOX_CI_TEST') != 'true',` to `DSS_RUN_CI_TEST`
- [x] in file `test/test_install_dependencies.py`: rename `TEST_CONTAINER_IMAGE_TAG = "script_languages_developer_sandbox_test_container:latest"` to `data_science_sandbox_test_container:latest`
- [x] in file `test/test_release_build.py`: rename `UPLOAD_URL = "https://uploads.github.com/repos/exasol/script-languages-developer-sandbox/releases/12` to `data-science-sandbox`
- [x] in file `test/test_release_build.py`: rename `StackResource({'LogicalResourceId': 'developerSandboxReleaseCodeBuild',` to `dataScienceSandboxReleaseCodeBuild`
```
